#!/bin/sh
# $Id: elisp-comp,v 1.1.1.1 1999/11/05 01:10:21 khan Exp $
# Trivial script to compile the Elisp files.
setpath=${TMPDIR-/tmp}/elc.$$
echo "(setq load-path (cons nil load-path))" > $setpath
emacs -batch -l $setpath -f batch-byte-compile "$@"
rm -f $setpath
